version: '3.8'

services:
  dev:
    container_name: clocktracker-dev
    image: node:lts
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - NUXT_PUBLIC_ASSET_VERSION=v1
    command: sh -c "npm install && npm run dev"
    stdin_open: true
    tty: true

volumes:
  node_modules:
